### ISSUE TITLE
Linux Step 4/5 swap Readme.md

### ISSUE THREAD

**Issue by Echosky** [giuseppe-dandrea/Stream-to-VLC#1]
In Linux,

Steps 4 should be Step 5, and Step 5 should be Step 4.  The .desktop file is not present otherwise before modifying string.  

*New here otherwise I would do a pull request.

**Comment by giuseppe-dandrea** [comment]
The steps are interchangeable, you should download the .desktop file from the repo, then you can copy and modify it or modify it and then copy, it's not different

**Comment by Echosky** [comment]
The instructions are ambiguous, the instructions mention to grab the plugin for Tampermonkey, however, there is no explicit direction given to download "vlc-stream" files.  Maybe I'm being pedantic, I understand you separated the instructions for both Linux and Windows.  Both of which, run well, however, how does one learn about these files unless specifically instructed to download and acquire them?  Just as the script instructions were given.

**Comment by giuseppe-dandrea** [comment]
Thanks for the feedback, it should be better now.
