### ISSUE TITLE
Add my own website

### ISSUE THREAD

**Issue by ahmadby100** [giuseppe-dandrea/Stream-to-VLC#4]
is there any way i can add my own website to the script?
I have a site where i host my own stuff but it will only play in browser or download if unsupported format?

I'd really appreciate it if you could guide me as to how I could add my own site

Thank you

**Comment by giuseppe-dandrea** [comment]
Hi, sorry for the late response, take a look at the code, it should be pretty straightforward. You should find the selector of the video from the page source and call the function `play_url(src)` using as argument, the src of the video.
Let me know if you need more info.
